name: Build_Windows

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Install packages
      run: 
        cd ~
        wget https://github.com/downloads/chokkan/liblbfgs/liblbfgs-1.10.tar.gz
        tar -xvzf liblbfgs-1.10.tar.gz
        cd liblbfgs-1.10
        ./configure
        make
        sudo make install
        
        cd ~
        wget https://github.com/downloads/chokkan/crfsuite/crfsuite-0.12.tar.gz
        tar -xvzf crfsuite-0.12.tar.gz
        cd crfsuite-0.12
        ./configure
        make
        sudo make install

        sudo apt-get -y install sqlite3 libsqlite3-dev
        sudo apt-get -y install libboost-all-dev
        sudo apt-get -y install libncurses-dev
    - name: Build
      run: 
        cd src
        mkdir build
        cd build
        cmake ..
        make
